name: diginodes
description: diginodes
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  socket_io: ^0.9.0+2
  crypto: any
  cryptoutils: any
  bignum:
    git: https://github.com/nseidm1/dart-bignum.git
  bitcoin:
    git: https://github.com/nseidm1/dart-bitcoin.git
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
